/**
 * lib/publishing/infoboard/screen1-admin-summary.ts
 *
 * Pure, deterministic admin-summary helper for Infoboard Screen 1.
 *
 * Derives administration-facing KPI counts and a flat, ordered event list
 * from an already-built InfoboardScreen1Feed. No DB access, no publication
 * policy evaluation, no temporal logic — all delegated upstream.
 *
 * Design constraints:
 *   - No Prisma import, no DB access, no Next.js, no React.
 *   - No new Date() calls — the feed already carries all temporal context.
 *   - No publication-policy logic — decisions were made in the feed builder.
 *   - No temporal-grouping logic — bucket classification already in the feed.
 *   - Inputs are never mutated.
 *   - Result arrays are always new arrays.
 *   - All properties on returned objects are derived from the feed.
 */

import type { InfoboardScreen1Feed, InfoboardScreen1Event, TemporalBucket } from "../event-types";

// ── Types ─────────────────────────────────────────────────────────────────────

/**
 * KPI counts derived from a Screen 1 feed for the admin overview.
 */
export type Screen1AdminCounts = {
  /** Total events in the feed (all buckets). */
  readonly visibleToday: number;
  /** Events in the "current" bucket (started, not yet over). */
  readonly currentCount: number;
  /** Events in the "next" bucket (the next upcoming group). */
  readonly nextCount: number;
  /** Events in the "later" bucket (later the same day). */
  readonly laterCount: number;
};

/**
 * A single entry in the flat admin event list.
 * All values come from the feed — no fabricated data.
 */
export type Screen1AdminEventEntry = {
  readonly id: string;
  readonly temporalBucket: TemporalBucket;
  readonly type: InfoboardScreen1Event["type"];
  readonly displayTitle: string;
  readonly teamDisplayName: string | null;
  readonly opponentDisplayName: string | null;
  readonly competitionLabel: string | null;
  readonly startAt: string;
  readonly endAt: string | null;
  readonly status: InfoboardScreen1Event["status"];
  readonly pitchLabel: string | null;
  readonly homeDressingRoomLabel: string | null;
  readonly awayDressingRoomLabel: string | null;
};

/**
 * Complete admin summary derived from a Screen 1 feed.
 */
export type Screen1AdminSummary = {
  readonly counts: Screen1AdminCounts;
  /**
   * All events from the feed flattened in display order:
   * current → next → later. Order within each bucket matches
   * the order in the feed (deterministic from the feed builder).
   */
  readonly events: readonly Screen1AdminEventEntry[];
  /** The display date key from the feed (YYYY-MM-DD, tenant local). */
  readonly displayDate: string;
};

// ── buildScreen1AdminSummary ──────────────────────────────────────────────────

/**
 * Derives an admin-facing summary from a pre-built Screen 1 feed.
 *
 * The feed must already be fully assembled (generated by buildScreen1LivePayload
 * or equivalent). This helper only reads from the feed — it adds no logic.
 *
 * @param feed - A fully assembled InfoboardScreen1Feed.
 * @returns Screen1AdminSummary with counts and a flat, ordered event list.
 */
export function buildScreen1AdminSummary(
  feed: InfoboardScreen1Feed,
): Screen1AdminSummary {
  // ── Counts ─────────────────────────────────────────────────────────────────
  const counts: Screen1AdminCounts = {
    visibleToday: feed.current.length + feed.next.length + feed.later.length,
    currentCount: feed.current.length,
    nextCount: feed.next.length,
    laterCount: feed.later.length,
  };

  // ── Flatten events in bucket order: current → next → later ─────────────────
  const allBuckets: Array<{ bucket: TemporalBucket; events: InfoboardScreen1Event[] }> = [
    { bucket: "current", events: feed.current },
    { bucket: "next", events: feed.next },
    { bucket: "later", events: feed.later },
  ];

  const events: Screen1AdminEventEntry[] = [];

  for (const { bucket, events: bucketEvents } of allBuckets) {
    for (const event of bucketEvents) {
      events.push({
        id: event.id,
        temporalBucket: bucket,
        type: event.type,
        displayTitle: event.displayTitle,
        teamDisplayName: event.teamDisplayName,
        opponentDisplayName: event.opponentDisplayName,
        competitionLabel: event.competitionLabel,
        startAt: event.startAt,
        endAt: event.endAt,
        status: event.status,
        pitchLabel: event.allocation.pitchLabel,
        homeDressingRoomLabel: event.allocation.homeDressingRoomLabel,
        awayDressingRoomLabel: event.allocation.awayDressingRoomLabel,
      });
    }
  }

  return {
    counts,
    events,
    displayDate: feed.displayDate,
  };
}
