export type WebsitePreset = {
  key: string;
  name: string;
  description: string;
  audienceClubType: string;
  visualTone: string;
  sportSuitability: string[];
  recommendedPages: string[];
  navigationStyle: string;
  homepageRhythm: string;
  previewTokens?: Record<string, string>;
};

export const WEBSITE_PRESETS: WebsitePreset[] = [
  {
    key: "classic-club",
    name: "Classic Club",
    description: "Zeitloser, seriöser Auftritt für etablierte Vereine mit breiter Mitgliederbasis.",
    audienceClubType: "Established amateur club, all ages",
    visualTone: "Clean, trustworthy, structured",
    sportSuitability: ["all"],
    recommendedPages: ["HOMEPAGE","TEAMS_OVERVIEW","TEAM_DETAIL","CLUB_ABOUT","EVENTS_OVERVIEW","NEWS_OVERVIEW","CONTACT"],
    navigationStyle: "horizontal-top",
    homepageRhythm: "hero → news-feed → events → team-grid → sponsors-bar",
    previewTokens: { primary: "#1a3a6b", accent: "#e8f0fb" },
  },
  {
    key: "modern-performance",
    name: "Modern Performance",
    description: "Dynamischer Auftritt für leistungsorientierte Clubs mit Fokus auf Resultate und Kader.",
    audienceClubType: "Performance-oriented club, competitive sport",
    visualTone: "Bold, energetic, data-forward",
    sportSuitability: ["football","basketball","handball","volleyball"],
    recommendedPages: ["HOMEPAGE","TEAMS_OVERVIEW","TEAM_DETAIL","EVENTS_OVERVIEW","NEWS_OVERVIEW","CONTACT"],
    navigationStyle: "horizontal-top with sticky",
    homepageRhythm: "full-width-hero → stats-row → event-list → team-grid → news-feed",
    previewTokens: { primary: "#0d0d0d", accent: "#ff3b00" },
  },
  {
    key: "community-club",
    name: "Community Club",
    description: "Herzlicher, einladender Auftritt für Vereine die Gemeinschaft in den Vordergrund stellen.",
    audienceClubType: "Community-focused club, family-friendly",
    visualTone: "Warm, open, welcoming",
    sportSuitability: ["all"],
    recommendedPages: ["HOMEPAGE","CLUB_ABOUT","EVENTS_OVERVIEW","REGISTRATION","NEWS_OVERVIEW","CONTACT"],
    navigationStyle: "horizontal-top",
    homepageRhythm: "hero → intro-text → events → registration-cta → news-feed → contact-info",
    previewTokens: { primary: "#1d6e3c", accent: "#f0f9f4" },
  },
  {
    key: "youth-academy",
    name: "Youth Academy",
    description: "Lebendiger Auftritt für Juniorenabteilungen mit Fokus auf Entwicklung und Elternkommunikation.",
    audienceClubType: "Junior/youth department, children & parents",
    visualTone: "Friendly, energetic, educational",
    sportSuitability: ["football","basketball","handball","volleyball","futsal"],
    recommendedPages: ["HOMEPAGE","TEAMS_OVERVIEW","TEAM_DETAIL","REGISTRATION","NEWS_OVERVIEW","CONTACT"],
    navigationStyle: "horizontal-top",
    homepageRhythm: "hero → team-grid → event-list → registration-cta → news-feed",
    previewTokens: { primary: "#f59e0b", accent: "#fffbeb" },
  },
  {
    key: "premium-sponsor-club",
    name: "Premium Sponsor Club",
    description: "Hochwertiger Auftritt für Vereine mit starken Sponsorenpartnerschaften und Business-Club.",
    audienceClubType: "Mid-to-upper tier club with business relationships",
    visualTone: "Premium, sophisticated, professional",
    sportSuitability: ["football","basketball","handball"],
    recommendedPages: ["HOMEPAGE","TEAMS_OVERVIEW","SPONSORS_PARTNERS","EVENTS_OVERVIEW","NEWS_OVERVIEW","CLUB_ABOUT","CONTACT"],
    navigationStyle: "horizontal-top with secondary bar",
    homepageRhythm: "hero → stats-row → sponsors-bar → news-feed → event-list → team-grid",
    previewTokens: { primary: "#1c1c1c", accent: "#c9a227" },
  },
  {
    key: "minimal-local-club",
    name: "Minimal Local Club",
    description: "Schlanker, wartungsarmer Auftritt für kleine Vereine mit begrenzten Ressourcen.",
    audienceClubType: "Small local club, volunteer-run",
    visualTone: "Simple, clear, low maintenance",
    sportSuitability: ["all"],
    recommendedPages: ["HOMEPAGE","EVENTS_OVERVIEW","CONTACT","LEGAL"],
    navigationStyle: "minimal single-row",
    homepageRhythm: "intro-text → event-list → contact-info",
    previewTokens: { primary: "#374151", accent: "#f9fafb" },
  },
  {
    key: "matchday-focus",
    name: "Matchday Focus",
    description: "Auftritt mit starkem Fokus auf Matchagenda, Resultate und Live-Updates.",
    audienceClubType: "Match-heavy club, fans and supporters",
    visualTone: "Sporty, live, action-oriented",
    sportSuitability: ["football","basketball","handball","volleyball","futsal"],
    recommendedPages: ["HOMEPAGE","EVENTS_OVERVIEW","TEAMS_OVERVIEW","NEWS_OVERVIEW","CONTACT"],
    navigationStyle: "horizontal-top",
    homepageRhythm: "hero → event-list → stats-row → news-feed → team-grid",
    previewTokens: { primary: "#16a34a", accent: "#f0fdf4" },
  },
  {
    key: "multi-sport-organisation",
    name: "Multi-Sport Organisation",
    description: "Strukturierter Auftritt für Vereine mit mehreren Sportabteilungen.",
    audienceClubType: "Multi-section club, diverse sports",
    visualTone: "Organised, structured, inclusive",
    sportSuitability: ["all"],
    recommendedPages: ["HOMEPAGE","TEAMS_OVERVIEW","TEAM_DETAIL","EVENTS_OVERVIEW","CLUB_ABOUT","REGISTRATION","NEWS_OVERVIEW","CONTACT"],
    navigationStyle: "horizontal with section tabs",
    homepageRhythm: "hero → team-grid → event-list → intro-text → sponsors-bar → news-feed",
    previewTokens: { primary: "#4f46e5", accent: "#eef2ff" },
  },
  {
    key: "event-community",
    name: "Event & Community",
    description: "Eventorientierter Auftritt für Vereine mit vielen Vereinsanlässen und Ehrenamt.",
    audienceClubType: "Event-active club, volunteers",
    visualTone: "Vibrant, social, community-driven",
    sportSuitability: ["all"],
    recommendedPages: ["HOMEPAGE","EVENTS_OVERVIEW","CLUB_ABOUT","REGISTRATION","NEWS_OVERVIEW","CONTACT"],
    navigationStyle: "horizontal-top",
    homepageRhythm: "hero → event-list → intro-text → registration-cta → news-feed",
    previewTokens: { primary: "#0891b2", accent: "#ecfeff" },
  },
  {
    key: "womens-sports-club",
    name: "Women's Sports Club",
    description: "Engagierter Auftritt mit Fokus auf Frauen- und Mädchensport.",
    audienceClubType: "Women's/girls sports section or club",
    visualTone: "Empowering, modern, bold",
    sportSuitability: ["football","volleyball","handball","basketball","tennis","fitness"],
    recommendedPages: ["HOMEPAGE","TEAMS_OVERVIEW","TEAM_DETAIL","REGISTRATION","NEWS_OVERVIEW","EVENTS_OVERVIEW","CONTACT"],
    navigationStyle: "horizontal-top",
    homepageRhythm: "hero → team-grid → registration-cta → event-list → news-feed",
    previewTokens: { primary: "#be185d", accent: "#fdf2f8" },
  },
  {
    key: "performance-academy",
    name: "Performance Academy",
    description: "Professioneller Auftritt für Akademien und Leistungszentren.",
    audienceClubType: "Academy, high-performance youth/junior",
    visualTone: "Professional, focused, developmental",
    sportSuitability: ["football","basketball","handball","tennis","fitness"],
    recommendedPages: ["HOMEPAGE","TEAMS_OVERVIEW","TEAM_DETAIL","CLUB_ABOUT","REGISTRATION","NEWS_OVERVIEW","CONTACT"],
    navigationStyle: "horizontal-top with sticky",
    homepageRhythm: "full-width-hero → intro-text → team-grid → stats-row → news-feed → registration-cta",
    previewTokens: { primary: "#1e3a5f", accent: "#e8f4fd" },
  },
  {
    key: "heritage-club",
    name: "Heritage Club",
    description: "Traditionsbewusster Auftritt für Vereine mit langer Geschichte.",
    audienceClubType: "Historic club with long tradition",
    visualTone: "Classic, dignified, timeless",
    sportSuitability: ["all"],
    recommendedPages: ["HOMEPAGE","CLUB_ABOUT","TEAMS_OVERVIEW","NEWS_OVERVIEW","EVENTS_OVERVIEW","CONTACT","LEGAL"],
    navigationStyle: "horizontal-top",
    homepageRhythm: "hero → intro-text → stats-row → news-feed → event-list → team-grid",
    previewTokens: { primary: "#78350f", accent: "#fef3c7" },
  },
  {
    key: "bold-digital-club",
    name: "Bold Digital Club",
    description: "Mutig-digitaler Auftritt für Clubs die online Präsenz in den Vordergrund stellen.",
    audienceClubType: "Digital-first club, younger audience",
    visualTone: "Bold, digital, content-rich",
    sportSuitability: ["all"],
    recommendedPages: ["HOMEPAGE","TEAMS_OVERVIEW","NEWS_OVERVIEW","EVENTS_OVERVIEW","CONTACT"],
    navigationStyle: "full-width-top",
    homepageRhythm: "full-width-hero → news-feed → event-list → team-grid → sponsors-bar",
    previewTokens: { primary: "#7c3aed", accent: "#f5f3ff" },
  },
  {
    key: "family-friendly-club",
    name: "Family Friendly Club",
    description: "Herzlicher Familienauftritt für Vereine die alle Generationen ansprechen.",
    audienceClubType: "Family club, all generations",
    visualTone: "Friendly, approachable, colourful",
    sportSuitability: ["all"],
    recommendedPages: ["HOMEPAGE","TEAMS_OVERVIEW","EVENTS_OVERVIEW","REGISTRATION","NEWS_OVERVIEW","CLUB_ABOUT","CONTACT"],
    navigationStyle: "horizontal-top",
    homepageRhythm: "hero → event-list → team-grid → registration-cta → news-feed → sponsors-bar",
    previewTokens: { primary: "#0369a1", accent: "#e0f2fe" },
  },
  {
    key: "sponsor-business-focus",
    name: "Sponsor & Business Focus",
    description: "Geschäftsorientierter Auftritt mit prominenter Sponsorenplatzierung.",
    audienceClubType: "Business-club-heavy, sponsorship-driven",
    visualTone: "Corporate, premium, commercial",
    sportSuitability: ["all"],
    recommendedPages: ["HOMEPAGE","SPONSORS_PARTNERS","EVENTS_OVERVIEW","TEAMS_OVERVIEW","CLUB_ABOUT","NEWS_OVERVIEW","CONTACT"],
    navigationStyle: "horizontal-top with secondary bar",
    homepageRhythm: "hero → sponsors-bar → stats-row → event-list → news-feed → registration-cta",
    previewTokens: { primary: "#064e3b", accent: "#ecfdf5" },
  },
  {
    key: "elite-youth-development",
    name: "Elite Youth Development",
    description: "Hochwertiger Auftritt für Nachwuchsleistungszentren mit Fokus auf Förderung, Kader und Akademie.",
    audienceClubType: "Elite youth academy, talent development centre",
    visualTone: "Aspirational, professional, structured",
    sportSuitability: ["football", "basketball", "handball", "tennis", "fitness"],
    recommendedPages: ["HOMEPAGE","TEAMS_OVERVIEW","TEAM_DETAIL","CLUB_ABOUT","REGISTRATION","NEWS_OVERVIEW","CONTACT"],
    navigationStyle: "horizontal-top with sticky",
    homepageRhythm: "full-width-hero → stats-row → team-grid → intro-text → news-feed → registration-cta",
    previewTokens: { primary: "#1a2e4a", accent: "#e8ecf0" },
  },
  {
    key: "classic-volunteer-club",
    name: "Classic Volunteer Club",
    description: "Ehrlicher, praktischer Auftritt für ehrenamtlich geführte Vereine ohne grossen Webauftritt-Aufwand.",
    audienceClubType: "Volunteer-run grassroots club",
    visualTone: "Honest, practical, low-effort",
    sportSuitability: ["all"],
    recommendedPages: ["HOMEPAGE","EVENTS_OVERVIEW","CLUB_ABOUT","CONTACT","LEGAL"],
    navigationStyle: "minimal single-row",
    homepageRhythm: "hero → event-list → intro-text → contact-info",
    previewTokens: { primary: "#3b5f3b", accent: "#f0f5f0" },
  },
  {
    key: "tournament-host",
    name: "Tournament Host",
    description: "Turnierspezifischer Auftritt für Vereine die als Gastgeber für regionale und nationale Turniere auftreten.",
    audienceClubType: "Tournament-hosting club, event organiser",
    visualTone: "Official, structured, event-forward",
    sportSuitability: ["football", "basketball", "handball", "volleyball", "futsal", "tennis"],
    recommendedPages: ["HOMEPAGE","EVENTS_OVERVIEW","TEAMS_OVERVIEW","SPONSORS_PARTNERS","CLUB_ABOUT","CONTACT","REGISTRATION"],
    navigationStyle: "horizontal-top with secondary bar",
    homepageRhythm: "full-width-hero → event-list → sponsors-bar → team-grid → registration-cta → news-feed",
    previewTokens: { primary: "#b45309", accent: "#fef9ee" },
  },
  {
    key: "urban-multi-sport",
    name: "Urban Multi-Sport",
    description: "Moderner, urbaner Auftritt für Sportzentren und Vereine in städtischen Umgebungen mit diversen Angeboten.",
    audienceClubType: "Urban sports centre, diverse city club",
    visualTone: "Urban, dynamic, inclusive, modern",
    sportSuitability: ["all"],
    recommendedPages: ["HOMEPAGE","TEAMS_OVERVIEW","EVENTS_OVERVIEW","REGISTRATION","NEWS_OVERVIEW","SPONSORS_PARTNERS","CONTACT"],
    navigationStyle: "full-width-top",
    homepageRhythm: "full-width-hero → team-grid → event-list → stats-row → sponsors-bar → registration-cta",
    previewTokens: { primary: "#1f2937", accent: "#f3f4f6" },
  },
  {
    key: "sponsor-showcase-pro",
    name: "Sponsor Showcase Pro",
    description: "Maximale Sichtbarkeit für Sponsoren und Unternehmenspartner. Ideal für Clubs mit starkem Business-Club-Angebot.",
    audienceClubType: "Sponsor-centric club, Business Club host",
    visualTone: "Executive, polished, high-visibility",
    sportSuitability: ["football", "basketball", "handball"],
    recommendedPages: ["HOMEPAGE","SPONSORS_PARTNERS","EVENTS_OVERVIEW","TEAMS_OVERVIEW","CLUB_ABOUT","NEWS_OVERVIEW","CONTACT"],
    navigationStyle: "horizontal-top with secondary bar",
    homepageRhythm: "full-width-hero → sponsors-bar → stats-row → event-list → team-grid → news-feed",
    previewTokens: { primary: "#18181b", accent: "#fafafa" },
  },
];

export function getWebsitePresetByKey(key: string): WebsitePreset | undefined {
  return WEBSITE_PRESETS.find((p) => p.key === key);
}
