export type WebsitePreset = {
  key: string;
  name: string;
  description: string;
  audienceClubType: string;
  visualTone: string;
  sportSuitability: string[];
  recommendedPages: string[];
  navigationStyle: string;
  homepageRhythm: string;
  bestUsedWhen: string;
  notIdealWhen: string;
  setupTip: string;
  firstRecommendedAction: string;
  previewTokens?: Record<string, string>;
};

export const WEBSITE_PRESETS: WebsitePreset[] = [
  {
    key: "classic-club",
    name: "Classic Club",
    description: "Zeitloser, seriöser Auftritt für etablierte Vereine mit breiter Mitgliederbasis.",
    audienceClubType: "Established amateur club, all ages",
    visualTone: "Clean, trustworthy, structured",
    sportSuitability: ["all"],
    recommendedPages: ["HOMEPAGE","TEAMS_OVERVIEW","TEAM_DETAIL","CLUB_ABOUT","EVENTS_OVERVIEW","NEWS_OVERVIEW","CONTACT"],
    navigationStyle: "horizontal-top",
    homepageRhythm: "hero → news-feed → events → team-grid → sponsors-bar",
    bestUsedWhen: "Der Verein hat eine breite Mitgliederbasis und möchte einen vertrauenswürdigen, stabilen Auftritt.",
    notIdealWhen: "Der Club sucht einen modernen, auffälligen Auftritt für ein jüngeres, digitales Publikum.",
    setupTip: "Halte die Teamseiten und den Newsfeed aktuell – das sind die am häufigsten besuchten Seiten.",
    firstRecommendedAction: "Homepage importieren und Logo, Vereinsname sowie Kurzbeschreibung eintragen.",
    previewTokens: { primary: "#1a3a6b", accent: "#e8f0fb" },
  },
  {
    key: "modern-performance",
    name: "Modern Performance",
    description: "Dynamischer Auftritt für leistungsorientierte Clubs mit Fokus auf Resultate und Kader.",
    audienceClubType: "Performance-oriented club, competitive sport",
    visualTone: "Bold, energetic, data-forward",
    sportSuitability: ["football","basketball","handball","volleyball"],
    recommendedPages: ["HOMEPAGE","TEAMS_OVERVIEW","TEAM_DETAIL","EVENTS_OVERVIEW","NEWS_OVERVIEW","CONTACT"],
    navigationStyle: "horizontal-top with sticky",
    homepageRhythm: "full-width-hero → stats-row → event-list → team-grid → news-feed",
    bestUsedWhen: "Der Club hat eine starke erste Mannschaft und möchte Leistungen, Resultate und Kader betonen.",
    notIdealWhen: "Der Verein ist hauptsächlich familien- oder gemeinschaftsorientiert ohne Wettkampffokus.",
    setupTip: "Befülle die Statistik-Zeile mit echten Saisonkennzahlen – das stärkt die Professionalität.",
    firstRecommendedAction: "Fullscreen-Hero und Statistik-Zeile auf der Homepage einrichten.",
    previewTokens: { primary: "#0d0d0d", accent: "#ff3b00" },
  },
  {
    key: "community-club",
    name: "Community Club",
    description: "Herzlicher, einladender Auftritt für Vereine die Gemeinschaft in den Vordergrund stellen.",
    audienceClubType: "Community-focused club, family-friendly",
    visualTone: "Warm, open, welcoming",
    sportSuitability: ["all"],
    recommendedPages: ["HOMEPAGE","CLUB_ABOUT","EVENTS_OVERVIEW","REGISTRATION","NEWS_OVERVIEW","CONTACT"],
    navigationStyle: "horizontal-top",
    homepageRhythm: "hero → intro-text → events → registration-cta → news-feed → contact-info",
    bestUsedWhen: "Gemeinschaft, Inklusion und Zusammenhalt stehen im Mittelpunkt des Vereinslebens.",
    notIdealWhen: "Der Fokus liegt primär auf sportlicher Leistung, Wettbewerb oder Sponsoring.",
    setupTip: "Setze die Anmeldungsseite früh auf – sie ist das wichtigste Ziel für Neuzugänge.",
    firstRecommendedAction: "Anmeldungsseite mit Registration-CTA und Kontaktdaten erstellen.",
    previewTokens: { primary: "#1d6e3c", accent: "#f0f9f4" },
  },
  {
    key: "youth-academy",
    name: "Youth Academy",
    description: "Lebendiger Auftritt für Juniorenabteilungen mit Fokus auf Entwicklung und Elternkommunikation.",
    audienceClubType: "Junior/youth department, children & parents",
    visualTone: "Friendly, energetic, educational",
    sportSuitability: ["football","basketball","handball","volleyball","futsal"],
    recommendedPages: ["HOMEPAGE","TEAMS_OVERVIEW","TEAM_DETAIL","REGISTRATION","NEWS_OVERVIEW","CONTACT"],
    navigationStyle: "horizontal-top",
    homepageRhythm: "hero → team-grid → event-list → registration-cta → news-feed",
    bestUsedWhen: "Die Juniorenabteilung ist der Kern des Vereins und Eltern suchen regelmässig nach Infos.",
    notIdealWhen: "Der Verein möchte primär die Erwachsenenmannschaft oder Sponsoring hervorheben.",
    setupTip: "Erstelle für jede Alterskategorie eine eigene Teamseite mit Trainer und Trainingszeiten.",
    firstRecommendedAction: "Teamübersicht nach Kategorien (G, F, E, D, etc.) aufbauen und Anmeldung verlinken.",
    previewTokens: { primary: "#f59e0b", accent: "#fffbeb" },
  },
  {
    key: "premium-sponsor-club",
    name: "Premium Sponsor Club",
    description: "Hochwertiger Auftritt für Vereine mit starken Sponsorenpartnerschaften und Business-Club.",
    audienceClubType: "Mid-to-upper tier club with business relationships",
    visualTone: "Premium, sophisticated, professional",
    sportSuitability: ["football","basketball","handball"],
    recommendedPages: ["HOMEPAGE","TEAMS_OVERVIEW","SPONSORS_PARTNERS","EVENTS_OVERVIEW","NEWS_OVERVIEW","CLUB_ABOUT","CONTACT"],
    navigationStyle: "horizontal-top with secondary bar",
    homepageRhythm: "hero → stats-row → sponsors-bar → news-feed → event-list → team-grid",
    bestUsedWhen: "Der Club pflegt aktive Sponsorenbeziehungen und möchte Partner prominent platzieren.",
    notIdealWhen: "Der Verein ist ein Breitensportclub ohne nennenswerte Sponsoring-Strukturen.",
    setupTip: "Pflege die Sponsorenseite sorgfältig mit Logos und Links – Sponsoren schätzen sichtbare Präsenz.",
    firstRecommendedAction: "Sponsorenseite mit Business-Club-Logos aufbauen und Homepage-Sponsorenzeile einrichten.",
    previewTokens: { primary: "#1c1c1c", accent: "#c9a227" },
  },
  {
    key: "minimal-local-club",
    name: "Minimal Local Club",
    description: "Schlanker, wartungsarmer Auftritt für kleine Vereine mit begrenzten Ressourcen.",
    audienceClubType: "Small local club, volunteer-run",
    visualTone: "Simple, clear, low maintenance",
    sportSuitability: ["all"],
    recommendedPages: ["HOMEPAGE","EVENTS_OVERVIEW","CONTACT","LEGAL"],
    navigationStyle: "minimal single-row",
    homepageRhythm: "intro-text → event-list → contact-info",
    bestUsedWhen: "Der Verein hat wenig Zeit für Webpflege und braucht eine einfache, funktionierende Lösung.",
    notIdealWhen: "Der Club möchte aktiv Content pflegen, Kader zeigen oder Sponsoring abbilden.",
    setupTip: "Beschränke dich auf wenige Seiten – lieber 3 gute als 10 halbfertige.",
    firstRecommendedAction: "Einzige Homepage mit Veranstaltungskalender und Kontaktdaten erstellen.",
    previewTokens: { primary: "#374151", accent: "#f9fafb" },
  },
  {
    key: "matchday-focus",
    name: "Matchday Focus",
    description: "Auftritt mit starkem Fokus auf Matchagenda, Resultate und Live-Updates.",
    audienceClubType: "Match-heavy club, fans and supporters",
    visualTone: "Sporty, live, action-oriented",
    sportSuitability: ["football","basketball","handball","volleyball","futsal"],
    recommendedPages: ["HOMEPAGE","EVENTS_OVERVIEW","TEAMS_OVERVIEW","NEWS_OVERVIEW","CONTACT"],
    navigationStyle: "horizontal-top",
    homepageRhythm: "hero → event-list → stats-row → news-feed → team-grid",
    bestUsedWhen: "Die Fangemeinde ist gross und sucht primär Spielinformationen, Ergebnisse und Agenda.",
    notIdealWhen: "Der Club hat kaum Matchbetrieb oder keinen starken Fanbereich.",
    setupTip: "Synchronisiere Events aus dem Saisonplanner damit die Spielagenda immer aktuell ist.",
    firstRecommendedAction: "Event-Übersicht als erste Seite nach der Homepage einrichten.",
    previewTokens: { primary: "#16a34a", accent: "#f0fdf4" },
  },
  {
    key: "multi-sport-organisation",
    name: "Multi-Sport Organisation",
    description: "Strukturierter Auftritt für Vereine mit mehreren Sportabteilungen.",
    audienceClubType: "Multi-section club, diverse sports",
    visualTone: "Organised, structured, inclusive",
    sportSuitability: ["all"],
    recommendedPages: ["HOMEPAGE","TEAMS_OVERVIEW","TEAM_DETAIL","EVENTS_OVERVIEW","CLUB_ABOUT","REGISTRATION","NEWS_OVERVIEW","CONTACT"],
    navigationStyle: "horizontal with section tabs",
    homepageRhythm: "hero → team-grid → event-list → intro-text → sponsors-bar → news-feed",
    bestUsedWhen: "Der Verein bietet mehrere Sportarten an und jede Abteilung soll sichtbar sein.",
    notIdealWhen: "Der Club fokussiert auf eine Sportart und möchte klare, sportspezifische Kommunikation.",
    setupTip: "Erstelle Teamseiten pro Sportart und nutze Kategorien für eine klare Struktur.",
    firstRecommendedAction: "Teamübersicht mit allen Sportabteilungen aufbauen und kategorisieren.",
    previewTokens: { primary: "#4f46e5", accent: "#eef2ff" },
  },
  {
    key: "event-community",
    name: "Event & Community",
    description: "Eventorientierter Auftritt für Vereine mit vielen Vereinsanlässen und Ehrenamt.",
    audienceClubType: "Event-active club, volunteers",
    visualTone: "Vibrant, social, community-driven",
    sportSuitability: ["all"],
    recommendedPages: ["HOMEPAGE","EVENTS_OVERVIEW","CLUB_ABOUT","REGISTRATION","NEWS_OVERVIEW","CONTACT"],
    navigationStyle: "horizontal-top",
    homepageRhythm: "hero → event-list → intro-text → registration-cta → news-feed",
    bestUsedWhen: "Der Verein organisiert viele Events und Ehrenamtliche sind ein zentrales Thema.",
    notIdealWhen: "Der Club hat kaum Vereinsanlässe und kommuniziert hauptsächlich über Sport.",
    setupTip: "Pflege den Veranstaltungskalender aktiv – er ist das Herzstück dieses Presets.",
    firstRecommendedAction: "Veranstaltungsübersicht als zentrale Seite einrichten und Events eintragen.",
    previewTokens: { primary: "#0891b2", accent: "#ecfeff" },
  },
  {
    key: "womens-sports-club",
    name: "Women's Sports Club",
    description: "Engagierter Auftritt mit Fokus auf Frauen- und Mädchensport.",
    audienceClubType: "Women's/girls sports section or club",
    visualTone: "Empowering, modern, bold",
    sportSuitability: ["football","volleyball","handball","basketball","tennis","fitness"],
    recommendedPages: ["HOMEPAGE","TEAMS_OVERVIEW","TEAM_DETAIL","REGISTRATION","NEWS_OVERVIEW","EVENTS_OVERVIEW","CONTACT"],
    navigationStyle: "horizontal-top",
    homepageRhythm: "hero → team-grid → registration-cta → event-list → news-feed",
    bestUsedWhen: "Die Frauenabteilung ist eigenständig oder möchte als Schwerpunkt des Vereins positioniert werden.",
    notIdealWhen: "Der Verein möchte alle Mannschaften gleichwertig ohne Schwerpunkt darstellen.",
    setupTip: "Zeige weibliche Vorbilder und Trainer-Profile prominent – das stärkt die Identifikation.",
    firstRecommendedAction: "Homepage mit starkem Hero und Anmeldungsaufruf für Neuzugänge aufbauen.",
    previewTokens: { primary: "#be185d", accent: "#fdf2f8" },
  },
  {
    key: "performance-academy",
    name: "Performance Academy",
    description: "Professioneller Auftritt für Akademien und Leistungszentren.",
    audienceClubType: "Academy, high-performance youth/junior",
    visualTone: "Professional, focused, developmental",
    sportSuitability: ["football","basketball","handball","tennis","fitness"],
    recommendedPages: ["HOMEPAGE","TEAMS_OVERVIEW","TEAM_DETAIL","CLUB_ABOUT","REGISTRATION","NEWS_OVERVIEW","CONTACT"],
    navigationStyle: "horizontal-top with sticky",
    homepageRhythm: "full-width-hero → intro-text → team-grid → stats-row → news-feed → registration-cta",
    bestUsedWhen: "Die Akademie positioniert sich als Talentförderungseinrichtung gegenüber Eltern und Spielern.",
    notIdealWhen: "Es geht um Breitensport oder lokale Gemeinschaft ohne Leistungsanspruch.",
    setupTip: "Dokumentiere Erfolgsstorys von Alumni und Kaderaufnahmen – das stärkt die Akademie-Positionierung.",
    firstRecommendedAction: "Über-uns-Seite mit Philosophie und Trainerstab aufbauen.",
    previewTokens: { primary: "#1e3a5f", accent: "#e8f4fd" },
  },
  {
    key: "heritage-club",
    name: "Heritage Club",
    description: "Traditionsbewusster Auftritt für Vereine mit langer Geschichte.",
    audienceClubType: "Historic club with long tradition",
    visualTone: "Classic, dignified, timeless",
    sportSuitability: ["all"],
    recommendedPages: ["HOMEPAGE","CLUB_ABOUT","TEAMS_OVERVIEW","NEWS_OVERVIEW","EVENTS_OVERVIEW","CONTACT","LEGAL"],
    navigationStyle: "horizontal-top",
    homepageRhythm: "hero → intro-text → stats-row → news-feed → event-list → team-grid",
    bestUsedWhen: "Der Verein feiert Jubiläen, pflegt Tradition und möchte Geschichte sichtbar machen.",
    notIdealWhen: "Der Club ist jung und möchte frisch und modern wirken.",
    setupTip: "Nutze die Über-uns-Seite für eine Vereinschronik mit Meilensteinen und historischen Fotos.",
    firstRecommendedAction: "Über-uns-Seite mit Gründungsgeschichte und Eckdaten aufbauen.",
    previewTokens: { primary: "#78350f", accent: "#fef3c7" },
  },
  {
    key: "bold-digital-club",
    name: "Bold Digital Club",
    description: "Mutig-digitaler Auftritt für Clubs die online Präsenz in den Vordergrund stellen.",
    audienceClubType: "Digital-first club, younger audience",
    visualTone: "Bold, digital, content-rich",
    sportSuitability: ["all"],
    recommendedPages: ["HOMEPAGE","TEAMS_OVERVIEW","NEWS_OVERVIEW","EVENTS_OVERVIEW","CONTACT"],
    navigationStyle: "full-width-top",
    homepageRhythm: "full-width-hero → news-feed → event-list → team-grid → sponsors-bar",
    bestUsedWhen: "Der Club hat aktive Content-Ersteller und Social-Media-Präsenz, die sich im Web widerspiegeln soll.",
    notIdealWhen: "Der Verein hat wenig Content-Ressourcen und kann die Seiten nicht regelmässig befüllen.",
    setupTip: "Plane monatlich mindestens 2 News-Beiträge um den Newsfeed aktuell zu halten.",
    firstRecommendedAction: "Homepage mit starkem Fullscreen-Hero und aktuellem Newsfeed einrichten.",
    previewTokens: { primary: "#7c3aed", accent: "#f5f3ff" },
  },
  {
    key: "family-friendly-club",
    name: "Family Friendly Club",
    description: "Herzlicher Familienauftritt für Vereine die alle Generationen ansprechen.",
    audienceClubType: "Family club, all generations",
    visualTone: "Friendly, approachable, colourful",
    sportSuitability: ["all"],
    recommendedPages: ["HOMEPAGE","TEAMS_OVERVIEW","EVENTS_OVERVIEW","REGISTRATION","NEWS_OVERVIEW","CLUB_ABOUT","CONTACT"],
    navigationStyle: "horizontal-top",
    homepageRhythm: "hero → event-list → team-grid → registration-cta → news-feed → sponsors-bar",
    bestUsedWhen: "Der Verein möchte Familien mit Kindern ansprechen und Anmeldungen aller Altersgruppen fördern.",
    notIdealWhen: "Der Club kommuniziert primär mit Erwachsenen oder ist auf Leistungssport fokussiert.",
    setupTip: "Stelle die Anmeldungsseite und Kontaktdaten sehr sichtbar – Eltern wollen schnell Infos finden.",
    firstRecommendedAction: "Anmeldungsseite mit klaren Informationen zu Kategorien und Trainingszeiten erstellen.",
    previewTokens: { primary: "#0369a1", accent: "#e0f2fe" },
  },
  {
    key: "sponsor-business-focus",
    name: "Sponsor & Business Focus",
    description: "Geschäftsorientierter Auftritt mit prominenter Sponsorenplatzierung.",
    audienceClubType: "Business-club-heavy, sponsorship-driven",
    visualTone: "Corporate, premium, commercial",
    sportSuitability: ["all"],
    recommendedPages: ["HOMEPAGE","SPONSORS_PARTNERS","EVENTS_OVERVIEW","TEAMS_OVERVIEW","CLUB_ABOUT","NEWS_OVERVIEW","CONTACT"],
    navigationStyle: "horizontal-top with secondary bar",
    homepageRhythm: "hero → sponsors-bar → stats-row → event-list → news-feed → registration-cta",
    bestUsedWhen: "Sponsoring und Business-Club-Mitgliedschaften sind zentrale Einnahmequellen des Vereins.",
    notIdealWhen: "Der Club hat kaum Sponsoren und möchte primär Sport und Gemeinschaft kommunizieren.",
    setupTip: "Aktualisiere die Sponsorenseite bei jedem neuen Partner sofort – das zeigt Verlässlichkeit.",
    firstRecommendedAction: "Sponsorenseite aufbauen und Sponsorenzeile auf der Homepage aktivieren.",
    previewTokens: { primary: "#064e3b", accent: "#ecfdf5" },
  },
  {
    key: "elite-youth-development",
    name: "Elite Youth Development",
    description: "Hochwertiger Auftritt für Nachwuchsleistungszentren mit Fokus auf Förderung, Kader und Akademie.",
    audienceClubType: "Elite youth academy, talent development centre",
    visualTone: "Aspirational, professional, structured",
    sportSuitability: ["football","basketball","handball","tennis","fitness"],
    recommendedPages: ["HOMEPAGE","TEAMS_OVERVIEW","TEAM_DETAIL","CLUB_ABOUT","REGISTRATION","NEWS_OVERVIEW","CONTACT"],
    navigationStyle: "horizontal-top with sticky",
    homepageRhythm: "full-width-hero → stats-row → team-grid → intro-text → news-feed → registration-cta",
    bestUsedWhen: "Das Zentrum fördert Talente strukturiert und kommuniziert mit Spielern, Eltern und Scouts.",
    notIdealWhen: "Es geht um Breitensport oder lokale Vereinstätigkeit ohne Leistungsstrukturen.",
    setupTip: "Dokumentiere Trainingsphilosophie und Erfolge früherer Jahrgänge auf der Über-uns-Seite.",
    firstRecommendedAction: "Über-uns-Seite mit Akademiekonzept, Trainerstab und Förderphilosophie aufbauen.",
    previewTokens: { primary: "#1a2e4a", accent: "#e8ecf0" },
  },
  {
    key: "classic-volunteer-club",
    name: "Classic Volunteer Club",
    description: "Ehrlicher, praktischer Auftritt für ehrenamtlich geführte Vereine ohne grossen Webauftritt-Aufwand.",
    audienceClubType: "Volunteer-run grassroots club",
    visualTone: "Honest, practical, low-effort",
    sportSuitability: ["all"],
    recommendedPages: ["HOMEPAGE","EVENTS_OVERVIEW","CLUB_ABOUT","CONTACT","LEGAL"],
    navigationStyle: "minimal single-row",
    homepageRhythm: "hero → event-list → intro-text → contact-info",
    bestUsedWhen: "Ehrenamtliche betreiben den Verein und haben begrenzte Zeit für Webpflege.",
    notIdealWhen: "Der Verein hat einen aktiven Content-Verantwortlichen und möchte regelmässig publizieren.",
    setupTip: "Konzentriere dich auf die Event-Seite und Kontakt – diese werden am häufigsten gesucht.",
    firstRecommendedAction: "Einzige Homepage mit Veranstaltungen, Kontakt und Impressum einrichten.",
    previewTokens: { primary: "#3b5f3b", accent: "#f0f5f0" },
  },
  {
    key: "tournament-host",
    name: "Tournament Host",
    description: "Turnierspezifischer Auftritt für Vereine die als Gastgeber für regionale und nationale Turniere auftreten.",
    audienceClubType: "Tournament-hosting club, event organiser",
    visualTone: "Official, structured, event-forward",
    sportSuitability: ["football","basketball","handball","volleyball","futsal","tennis"],
    recommendedPages: ["HOMEPAGE","EVENTS_OVERVIEW","TEAMS_OVERVIEW","SPONSORS_PARTNERS","CLUB_ABOUT","CONTACT","REGISTRATION"],
    navigationStyle: "horizontal-top with secondary bar",
    homepageRhythm: "full-width-hero → event-list → sponsors-bar → team-grid → registration-cta → news-feed",
    bestUsedWhen: "Der Club organisiert Turniere und Events für externe Teams und Gäste.",
    notIdealWhen: "Der Club nimmt an Turnieren teil, organisiert aber keine eigenen.",
    setupTip: "Erstelle für jedes Turnier eine separate Event-Seite mit allen Infos für auswärtige Teams.",
    firstRecommendedAction: "Veranstaltungsübersicht mit nächstem Turnier als Hauptevent einrichten.",
    previewTokens: { primary: "#b45309", accent: "#fef9ee" },
  },
  {
    key: "urban-multi-sport",
    name: "Urban Multi-Sport",
    description: "Moderner, urbaner Auftritt für Sportzentren und Vereine in städtischen Umgebungen mit diversen Angeboten.",
    audienceClubType: "Urban sports centre, diverse city club",
    visualTone: "Urban, dynamic, inclusive, modern",
    sportSuitability: ["all"],
    recommendedPages: ["HOMEPAGE","TEAMS_OVERVIEW","EVENTS_OVERVIEW","REGISTRATION","NEWS_OVERVIEW","SPONSORS_PARTNERS","CONTACT"],
    navigationStyle: "full-width-top",
    homepageRhythm: "full-width-hero → team-grid → event-list → stats-row → sponsors-bar → registration-cta",
    bestUsedWhen: "Das Sportzentrum richtet sich an ein urbanes, diverses Publikum mit mehreren Sportangeboten.",
    notIdealWhen: "Der Club ist ländlich geprägt und möchte einen traditionellen, lokalen Charakter ausstrahlen.",
    setupTip: "Hebe das vielfältige Angebot durch eine strukturierte Teamübersicht nach Sportarten hervor.",
    firstRecommendedAction: "Teamübersicht mit allen Sportangeboten und klaren Anmeldungslinks aufbauen.",
    previewTokens: { primary: "#1f2937", accent: "#f3f4f6" },
  },
  {
    key: "sponsor-showcase-pro",
    name: "Sponsor Showcase Pro",
    description: "Maximale Sichtbarkeit für Sponsoren und Unternehmenspartner. Ideal für Clubs mit starkem Business-Club-Angebot.",
    audienceClubType: "Sponsor-centric club, Business Club host",
    visualTone: "Executive, polished, high-visibility",
    sportSuitability: ["football","basketball","handball"],
    recommendedPages: ["HOMEPAGE","SPONSORS_PARTNERS","EVENTS_OVERVIEW","TEAMS_OVERVIEW","CLUB_ABOUT","NEWS_OVERVIEW","CONTACT"],
    navigationStyle: "horizontal-top with secondary bar",
    homepageRhythm: "full-width-hero → sponsors-bar → stats-row → event-list → team-grid → news-feed",
    bestUsedWhen: "Sponsoren sind strategische Partner und erwarten professionelle Online-Präsenz.",
    notIdealWhen: "Sponsoring spielt keine zentrale Rolle und der Fokus liegt auf Sport und Gemeinschaft.",
    setupTip: "Integriere Sponsor-Logos in mehreren Bereichen der Website für maximale Sichtbarkeit.",
    firstRecommendedAction: "Sponsorenseite mit Partnerlogos und Business-Club-Informationen erstellen.",
    previewTokens: { primary: "#18181b", accent: "#fafafa" },
  },
  {
    key: "handball-club",
    name: "Handball Club",
    description: "Dynamischer Auftritt für Handballvereine mit Fokus auf Spielplan und Kader.",
    audienceClubType: "Handball club, competitive and recreational",
    visualTone: "Athletic, team-focused, energetic",
    sportSuitability: ["handball"],
    recommendedPages: ["HOMEPAGE","TEAMS_OVERVIEW","TEAM_DETAIL","EVENTS_OVERVIEW","NEWS_OVERVIEW","CONTACT"],
    navigationStyle: "horizontal-top",
    homepageRhythm: "hero → stats-row → team-grid → event-list → news-feed",
    bestUsedWhen: "Der Verein spielt Handball auf Amateur- oder Leistungsebene mit aktivem Spielbetrieb.",
    notIdealWhen: "Der Club hat keine regelmässigen Spiele oder betreibt mehrere Sportarten.",
    setupTip: "Erstelle für jede Mannschaft (1. Liga, Junioren, Damen) eine eigene Teamseite.",
    firstRecommendedAction: "Teamübersicht nach Leistungsklassen aufbauen.",
    previewTokens: { primary: "#c2410c", accent: "#fff7ed" },
  },
  {
    key: "basketball-club",
    name: "Basketball Club",
    description: "Moderner Auftritt für Basketballvereine mit Fokus auf Resultate und Community.",
    audienceClubType: "Basketball club, all levels",
    visualTone: "Urban, modern, competitive",
    sportSuitability: ["basketball"],
    recommendedPages: ["HOMEPAGE","TEAMS_OVERVIEW","TEAM_DETAIL","EVENTS_OVERVIEW","NEWS_OVERVIEW","CONTACT"],
    navigationStyle: "horizontal-top with sticky",
    homepageRhythm: "full-width-hero → stats-row → event-list → team-grid → news-feed",
    bestUsedWhen: "Der Club hat aktiven Spielbetrieb und möchte Resultate und Kader prominent zeigen.",
    notIdealWhen: "Gemeinschaft und Breitensport stehen absolut im Vordergrund ohne Wettkampffokus.",
    setupTip: "Verknüpfe Spielplandaten direkt mit dem Event-Block für automatische Aktualisierungen.",
    firstRecommendedAction: "Homepage mit Spielplan der aktuellen Saison einrichten.",
    previewTokens: { primary: "#f97316", accent: "#fff7ed" },
  },
  {
    key: "volleyball-club",
    name: "Volleyball Club",
    description: "Frischer, teamorientierter Auftritt für Volleyballvereine.",
    audienceClubType: "Volleyball club, mixed and women's",
    visualTone: "Fresh, inclusive, sport-forward",
    sportSuitability: ["volleyball"],
    recommendedPages: ["HOMEPAGE","TEAMS_OVERVIEW","TEAM_DETAIL","REGISTRATION","EVENTS_OVERVIEW","NEWS_OVERVIEW","CONTACT"],
    navigationStyle: "horizontal-top",
    homepageRhythm: "hero → team-grid → event-list → registration-cta → news-feed",
    bestUsedWhen: "Der Club hat mehrere Mannschaften (Damen, Herren, Junioren) und aktiven Spielbetrieb.",
    notIdealWhen: "Hauptfokus liegt auf Freizeit und Sozialem ohne Wettkampfstruktur.",
    setupTip: "Hebe gemischte und Damen-Teams gleichwertig hervor um alle Mitglieder anzusprechen.",
    firstRecommendedAction: "Teamübersicht mit allen aktiven Mannschaften erstellen.",
    previewTokens: { primary: "#0284c7", accent: "#e0f2fe" },
  },
  {
    key: "esports-club",
    name: "Esports Club",
    description: "Digitaler, moderner Auftritt für Esports-Vereine und Gaming-Communities.",
    audienceClubType: "Esports club, gaming community",
    visualTone: "Digital, dark-accent, community-forward",
    sportSuitability: ["all"],
    recommendedPages: ["HOMEPAGE","TEAMS_OVERVIEW","TEAM_DETAIL","NEWS_OVERVIEW","EVENTS_OVERVIEW","REGISTRATION","CONTACT"],
    navigationStyle: "full-width-top",
    homepageRhythm: "full-width-hero → team-grid → event-list → stats-row → news-feed → registration-cta",
    bestUsedWhen: "Der Club betreibt strukturierten Spielbetrieb in digitalen Sportarten.",
    notIdealWhen: "Traditionelle Sportarten mit physischem Spielbetrieb sind das Hauptangebot.",
    setupTip: "Stelle Teamprofile mit Spielernamen und Disziplinen (League of Legends, FIFA, etc.) dar.",
    firstRecommendedAction: "Homepage mit aktivem Roster und nächstem Turnier aufbauen.",
    previewTokens: { primary: "#7c3aed", accent: "#faf5ff" },
  },
  {
    key: "municipality-cooperative",
    name: "Gemeinde & Kooperationsverein",
    description: "Strukturierter, offizieller Auftritt für gemeinnützige Sportvereine mit kommunaler Bindung.",
    audienceClubType: "Municipality-linked club, cooperative, public benefit",
    visualTone: "Official, structured, transparent",
    sportSuitability: ["all"],
    recommendedPages: ["HOMEPAGE","CLUB_ABOUT","TEAMS_OVERVIEW","EVENTS_OVERVIEW","REGISTRATION","NEWS_OVERVIEW","SPONSORS_PARTNERS","CONTACT","LEGAL"],
    navigationStyle: "horizontal-top with secondary bar",
    homepageRhythm: "hero → intro-text → team-grid → event-list → sponsors-bar → registration-cta",
    bestUsedWhen: "Der Verein ist gemeinnützig, eng mit der Gemeinde verbunden oder öffentlich finanziert.",
    notIdealWhen: "Privater Leistungssport oder kommerzielles Umfeld ist die Hauptausrichtung.",
    setupTip: "Transparenz über Struktur, Vorstand und Statuten schafft Vertrauen bei Förderstellen.",
    firstRecommendedAction: "Über-uns-Seite mit Vereinsstruktur, Vorstand und Förderpartnern aufbauen.",
    previewTokens: { primary: "#0f766e", accent: "#f0fdfa" },
  },
];

export function getWebsitePresetByKey(key: string): WebsitePreset | undefined {
  return WEBSITE_PRESETS.find((p) => p.key === key);
}
