import { PERMISSIONS, type PermissionKey } from "@/lib/permissions/permissions";

export const ROUTE_PERMISSION_SETS = {
  EVENTS_READ: [
    PERMISSIONS.EVENTS_VIEW,
    PERMISSIONS.EVENTS_MANAGE,
  ] satisfies PermissionKey[],

  PEOPLE_SEARCH: [
    PERMISSIONS.PEOPLE_VIEW,
    PERMISSIONS.TEAMS_MANAGE,
  ] satisfies PermissionKey[],

  SEASONS_READ: [
    PERMISSIONS.SEASONS_VIEW,
    PERMISSIONS.SEASONS_MANAGE,
    PERMISSIONS.TEAMS_VIEW,
    PERMISSIONS.TEAMS_MANAGE,
  ] satisfies PermissionKey[],

  TEAMS_READ: [
    PERMISSIONS.TEAMS_VIEW,
    PERMISSIONS.TEAMS_MANAGE,
    PERMISSIONS.EVENTS_VIEW,
    PERMISSIONS.EVENTS_MANAGE,
  ] satisfies PermissionKey[],

  MEETINGS_READ: [
    PERMISSIONS.MEETINGS_VIEW,
    PERMISSIONS.MEETINGS_MANAGE,
  ] satisfies PermissionKey[],

  INITIATIVES_READ: [
    PERMISSIONS.INITIATIVES_VIEW,
    PERMISSIONS.INITIATIVES_MANAGE,
  ] satisfies PermissionKey[],

  TARGETS_READ: [
    PERMISSIONS.TARGETS_VIEW,
    PERMISSIONS.TARGETS_MANAGE,
  ] satisfies PermissionKey[],
} as const;
