import { PERMISSIONS, type PermissionKey } from "@/lib/permissions/permissions";

export const ROUTE_PERMISSION_SETS = {
  EVENTS_READ: [
    PERMISSIONS.EVENTS_VIEW,
    PERMISSIONS.EVENTS_MANAGE,
  ] satisfies PermissionKey[],

  PEOPLE_SEARCH: [
    PERMISSIONS.PEOPLE_VIEW,
    PERMISSIONS.TEAMS_MANAGE,
  ] satisfies PermissionKey[],

  SEASONS_READ: [
    PERMISSIONS.SEASONS_VIEW,
    PERMISSIONS.SEASONS_MANAGE,
    PERMISSIONS.TEAMS_VIEW,
    PERMISSIONS.TEAMS_MANAGE,
  ] satisfies PermissionKey[],

  TEAMS_READ: [
    PERMISSIONS.TEAMS_VIEW,
    PERMISSIONS.TEAMS_MANAGE,
    PERMISSIONS.EVENTS_VIEW,
    PERMISSIONS.EVENTS_MANAGE,
  ] satisfies PermissionKey[],

  VEREINSLEITUNG_READ: [
    PERMISSIONS.VEREINSLEITUNG_VIEW,
    PERMISSIONS.VEREINSLEITUNG_KPI_VIEW,
    PERMISSIONS.VEREINSLEITUNG_PENDENZEN_VIEW,
    PERMISSIONS.VEREINSLEITUNG_PENDENZEN_MANAGE,
    PERMISSIONS.VEREINSLEITUNG_MEETINGS_VIEW,
    PERMISSIONS.VEREINSLEITUNG_MEETINGS_MANAGE,
    PERMISSIONS.VEREINSLEITUNG_INITIATIVES_VIEW,
    PERMISSIONS.VEREINSLEITUNG_INITIATIVES_MANAGE,
  ] satisfies PermissionKey[],

  VEREINSLEITUNG_COCKPIT_READ: [
    PERMISSIONS.VEREINSLEITUNG_VIEW,
    PERMISSIONS.VEREINSLEITUNG_KPI_VIEW,
    PERMISSIONS.VEREINSLEITUNG_PENDENZEN_VIEW,
    PERMISSIONS.VEREINSLEITUNG_PENDENZEN_MANAGE,
  ] satisfies PermissionKey[],

  VEREINSLEITUNG_MEETINGS_READ: [
    PERMISSIONS.VEREINSLEITUNG_MEETINGS_VIEW,
    PERMISSIONS.VEREINSLEITUNG_MEETINGS_MANAGE,
    PERMISSIONS.VEREINSLEITUNG_VIEW,
  ] satisfies PermissionKey[],

  VEREINSLEITUNG_INITIATIVES_READ: [
    PERMISSIONS.VEREINSLEITUNG_INITIATIVES_VIEW,
    PERMISSIONS.VEREINSLEITUNG_INITIATIVES_MANAGE,
    PERMISSIONS.VEREINSLEITUNG_VIEW,
  ] satisfies PermissionKey[],
} as const;
