export type InfoboardMode = "LIGHT" | "DARK" | "AUTO";
export type SponsorVisibility = "none" | "subtle" | "standard" | "prominent";
export type ScheduleDensity = "minimal" | "compact" | "full";

export type InfoboardPreset = {
  key: string;
  name: string;
  mode: InfoboardMode;
  description: string;
  bestUseCase: string;
  recommendedScreens: string[];
  layoutRhythm: string;
  sponsorVisibilityLevel: SponsorVisibility;
  scheduleDensity: ScheduleDensity;
  alertAnnouncementSupport: boolean;
  bestUsedWhen: string;
  notIdealWhen: string;
  setupTip: string;
  firstRecommendedAction: string;
  previewTokens?: Record<string, string>;
};

export const INFOBOARD_PRESETS: InfoboardPreset[] = [
  {
    key: "clean-light",
    name: "Clean Light",
    mode: "LIGHT",
    description: "Helles, übersichtliches Layout für gut beleuchtete Räume und Eingangsbereiche.",
    bestUseCase: "Reception, club house entrance, bright rooms",
    recommendedScreens: ["schedule", "news", "sponsors"],
    layoutRhythm: "header → today-schedule → upcoming-events → news-ticker",
    sponsorVisibilityLevel: "standard",
    scheduleDensity: "compact",
    alertAnnouncementSupport: true,
    bestUsedWhen: "Der Bildschirm hängt in einem hellen Raum und soll für alle Besucher lesbar sein.",
    notIdealWhen: "Der Screen läuft in einem abgedunkelten Raum oder Spieltag-Umgebung.",
    setupTip: "Stelle sicher dass der Spielplan täglich aktuell ist – er ist der meistbeachtetste Bereich.",
    firstRecommendedAction: "Tagesplan mit aktuellen Trainings- und Spielinfos verbinden.",
    previewTokens: { bg: "#ffffff", text: "#1e293b", accent: "#0b4aa2" },
  },
  {
    key: "clean-dark",
    name: "Clean Dark",
    mode: "DARK",
    description: "Dunkles, elegantes Layout für Trainingsräume und abgedunkelte Bildschirme.",
    bestUseCase: "Gym, training hall, low-light areas",
    recommendedScreens: ["schedule", "next-training", "team-info"],
    layoutRhythm: "header → next-event → today-schedule → news-ticker",
    sponsorVisibilityLevel: "subtle",
    scheduleDensity: "compact",
    alertAnnouncementSupport: true,
    bestUsedWhen: "Helles Layout zu stark kontrastiert oder der Bildschirm ist in einem abgedunkelten Raum.",
    notIdealWhen: "Das Umfeld ist sehr hell oder der Screen ist für Eltern/Gäste im Eingangsbereich.",
    setupTip: "Erhöhe die Schriftgrösse für bessere Lesbarkeit aus grösserem Abstand.",
    firstRecommendedAction: "Nächstes Training prominent im Hauptbereich anzeigen.",
    previewTokens: { bg: "#0f172a", text: "#f1f5f9", accent: "#38bdf8" },
  },
  {
    key: "matchday-dark",
    name: "Matchday Dark",
    mode: "DARK",
    description: "Dramatisches dunkles Layout für Spieltage mit Fokus auf Match-Infos und Ergebnisse.",
    bestUseCase: "Stadium, match venue, fan areas",
    recommendedScreens: ["matchday-schedule", "live-score", "lineup", "sponsors"],
    layoutRhythm: "fullscreen-hero → match-details → score → lineups → sponsors-bar",
    sponsorVisibilityLevel: "prominent",
    scheduleDensity: "minimal",
    alertAnnouncementSupport: true,
    bestUsedWhen: "Es ist Spieltag und die Atmosphäre soll dramatisch und fokussiert sein.",
    notIdealWhen: "Es ist kein Spieltag und normale Trainings-/Clubinformationen sollen gezeigt werden.",
    setupTip: "Aktiviere dieses Preset nur an Spieltagen und kehre danach zu einem Alltags-Preset zurück.",
    firstRecommendedAction: "Match-Details und Aufstellung für das nächste Heimspiel vorbereiten.",
    previewTokens: { bg: "#0a0a0a", text: "#ffffff", accent: "#22c55e" },
  },
  {
    key: "sponsor-premium",
    name: "Sponsor Premium",
    mode: "AUTO",
    description: "Hochwertiges Layout mit prominenter Sponsorenpräsenz für Business-Club-Umgebungen.",
    bestUseCase: "VIP lounge, hospitality area, sponsor events",
    recommendedScreens: ["sponsors", "schedule", "news", "stats"],
    layoutRhythm: "logo-bar → split-schedule-sponsor → news-ticker → full-sponsor-screen",
    sponsorVisibilityLevel: "prominent",
    scheduleDensity: "compact",
    alertAnnouncementSupport: false,
    bestUsedWhen: "Sponsoren und VIP-Gäste sind im Raum und die Bildschirme sollen Partnerpräsenz zeigen.",
    notIdealWhen: "Es ist ein öffentlicher Bereich für Fans oder der Fokus liegt auf dem Spielplan.",
    setupTip: "Rotiere Sponsor-Logos regelmässig damit alle Partner gleich viel Sichtbarkeit erhalten.",
    firstRecommendedAction: "Sponsor-Logos für die Rotation hochladen und Prioritäten festlegen.",
    previewTokens: { bg: "#1c1c1c", text: "#f5f5f5", accent: "#c9a227" },
  },
  {
    key: "youth-friendly",
    name: "Youth Friendly",
    mode: "LIGHT",
    description: "Farbenfroher, kinderfreundlicher Auftritt für Juniorenräume und Trainingsbereiche.",
    bestUseCase: "Youth training room, school club, kids area",
    recommendedScreens: ["schedule", "team-news", "next-training"],
    layoutRhythm: "colourful-header → today-schedule → team-of-the-week → news",
    sponsorVisibilityLevel: "none",
    scheduleDensity: "compact",
    alertAnnouncementSupport: false,
    bestUsedWhen: "Kinder und Jugendliche sind die Hauptzielgruppe des Bildschirmstandorts.",
    notIdealWhen: "Erwachsene Mannschaften oder Sponsor-Umgebungen sind die Zielgruppe.",
    setupTip: "Nutze kurze, einfache Texte und grosse Schriften für optimale Lesbarkeit für Kinder.",
    firstRecommendedAction: "Nächstes Juniorentraining mit Team-Namen und Ort anzeigen.",
    previewTokens: { bg: "#fffbeb", text: "#1c1917", accent: "#f59e0b" },
  },
  {
    key: "operations-board",
    name: "Operations Board",
    mode: "LIGHT",
    description: "Informationsdichtes Layout für Betriebsräume mit vollständiger Tagesagenda.",
    bestUseCase: "Admin office, operations room, staff area",
    recommendedScreens: ["full-schedule", "pitch-allocation", "roles", "announcements"],
    layoutRhythm: "date-header → full-day-schedule → pitch-grid → staff-notes",
    sponsorVisibilityLevel: "none",
    scheduleDensity: "full",
    alertAnnouncementSupport: true,
    bestUsedWhen: "Betriebsverantwortliche und Helfer brauchen die vollständige Tagesübersicht auf einen Blick.",
    notIdealWhen: "Öffentliche Bereiche oder Bereiche mit wechselndem Publikum sind die Zielgruppe.",
    setupTip: "Verbinde Platzbelegung und Helferplan direkt mit dem Board für minimalen Pflegeaufwand.",
    firstRecommendedAction: "Vollständigen Tagesplan mit Platz- und Garderobeninfos einrichten.",
    previewTokens: { bg: "#f8fafc", text: "#0f172a", accent: "#334155" },
  },
  {
    key: "minimal-schedule",
    name: "Minimal Schedule",
    mode: "AUTO",
    description: "Maximal reduziertes Layout das nur die wichtigsten Termininfos zeigt.",
    bestUseCase: "Corridor screen, secondary display, kiosk",
    recommendedScreens: ["next-3-events", "date-time"],
    layoutRhythm: "large-clock → next-events-list",
    sponsorVisibilityLevel: "none",
    scheduleDensity: "minimal",
    alertAnnouncementSupport: false,
    bestUsedWhen: "Durchgangsbereich oder Nebenbildschirm, auf dem nur die wichtigsten Infos gezeigt werden sollen.",
    notIdealWhen: "Hauptbildschirm im Eingangsbereich oder umfangreiche Informationen gezeigt werden müssen.",
    setupTip: "Beschränke die Anzeige auf maximal 3 kommende Events für klare Lesbarkeit.",
    firstRecommendedAction: "Die nächsten 3 Events aus dem Saisonplanner verbinden.",
    previewTokens: { bg: "#ffffff", text: "#111827", accent: "#6b7280" },
  },
  {
    key: "club-tv",
    name: "Club TV",
    mode: "DARK",
    description: "TV-ähnliches Layout mit automatischer Rotation für Eingangsbereiche und Lounges.",
    bestUseCase: "Main display, entrance TV, waiting area",
    recommendedScreens: ["schedule", "news", "sponsors", "team-highlights", "stats"],
    layoutRhythm: "rotating-hero → news-panel → schedule-strip → sponsor-ticker",
    sponsorVisibilityLevel: "standard",
    scheduleDensity: "compact",
    alertAnnouncementSupport: true,
    bestUsedWhen: "Hauptbildschirm im Eingangsbereich für Mitglieder, Gäste und Eltern.",
    notIdealWhen: "Spezialisierte Bereiche wie Operations, Spieltag oder VIP erfordern ein spezifisches Preset.",
    setupTip: "Stelle eine Rotation von 15–30 Sekunden pro Bildschirm ein für flüssige Präsentation.",
    firstRecommendedAction: "News-Feed, Spielplan und Sponsor-Logos für die automatische Rotation konfigurieren.",
    previewTokens: { bg: "#111827", text: "#f9fafb", accent: "#3b82f6" },
  },
  {
    key: "tournament-mode",
    name: "Tournament Mode",
    mode: "AUTO",
    description: "Turnieroptimiertes Layout mit Bracket-Support und Gruppenstand.",
    bestUseCase: "Tournament venue, multiple courts, event day",
    recommendedScreens: ["bracket", "group-standings", "next-matches", "results"],
    layoutRhythm: "tournament-header → bracket-display → results-stream → sponsors-bar",
    sponsorVisibilityLevel: "standard",
    scheduleDensity: "full",
    alertAnnouncementSupport: true,
    bestUsedWhen: "Ein Turnier mit mehreren Spielen findet statt und Ergebnisse sollen live angezeigt werden.",
    notIdealWhen: "Es ist kein Turniertag oder es gibt nur einzelne Spiele ohne Gruppenphase.",
    setupTip: "Aktiviere dieses Preset am Turniertag und deaktiviere es danach für den Normalbetrieb.",
    firstRecommendedAction: "Turnierspielplan mit Gruppen und Begegnungen vor dem Event einpflegen.",
    previewTokens: { bg: "#0c1a2e", text: "#e2e8f0", accent: "#f59e0b" },
  },
  {
    key: "emergency-announcement",
    name: "Emergency / Announcement Mode",
    mode: "AUTO",
    description: "Auffälliges Layout für Notfallmeldungen und wichtige Vereinsmitteilungen.",
    bestUseCase: "Club-wide announcements, emergency info, urgent updates",
    recommendedScreens: ["alert-message", "contact-info"],
    layoutRhythm: "fullscreen-alert → message-body → contact-strip",
    sponsorVisibilityLevel: "none",
    scheduleDensity: "minimal",
    alertAnnouncementSupport: true,
    bestUsedWhen: "Eine dringende Mitteilung muss sofort allen Personen auf dem Gelände angezeigt werden.",
    notIdealWhen: "Es ist keine Notfall- oder Sondersituation aktiv.",
    setupTip: "Bereite Vorlagen für häufige Ankündigungen vor um im Ernstfall schnell reagieren zu können.",
    firstRecommendedAction: "Vorlagen für Trainingsausfall, Platzsperrung und Notfalladressen vorbereiten.",
    previewTokens: { bg: "#7f1d1d", text: "#fef2f2", accent: "#ef4444" },
  },
  {
    key: "youth-matchday",
    name: "Youth Matchday",
    mode: "LIGHT",
    description: "Lebhaftes Spieltag-Layout für Juniorenmatchs mit farbiger Grafik und einfacher Lesbarkeit.",
    bestUseCase: "Youth match venue, junior pitch sideline screen",
    recommendedScreens: ["next-match", "team-lineup", "schedule", "news"],
    layoutRhythm: "colourful-header → match-details → team-lineup → next-events",
    sponsorVisibilityLevel: "subtle",
    scheduleDensity: "compact",
    alertAnnouncementSupport: false,
    bestUsedWhen: "Juniorenmatch-Tage wo Eltern und Kinder auf dem Vereinsgelände sind.",
    notIdealWhen: "Professionelle Matchumgebung oder Sponsor-VIP-Bereich ist die Zielgruppe.",
    setupTip: "Hebe die Aufstellung der Heimmannschaft hervor – das ist immer der meistbeachtete Bereich.",
    firstRecommendedAction: "Match-Details mit Aufstellung und Anpfiffzeit für das nächste Juniorenspiel einrichten.",
    previewTokens: { bg: "#fefce8", text: "#1c1917", accent: "#84cc16" },
  },
  {
    key: "sponsor-lounge",
    name: "Sponsor Lounge",
    mode: "DARK",
    description: "Exklusives dunkles Layout für Sponsor-Lounges und VIP-Bereiche mit rotating Logos.",
    bestUseCase: "VIP sponsor lounge, executive hospitality area",
    recommendedScreens: ["sponsor-showcase", "schedule", "news-highlights", "stats"],
    layoutRhythm: "fullscreen-sponsor → news-panel → schedule-strip → rotating-logos",
    sponsorVisibilityLevel: "prominent",
    scheduleDensity: "minimal",
    alertAnnouncementSupport: false,
    bestUsedWhen: "Exklusive Sponsorenlounges und VIP-Bereiche wo Partner eine prominent sichtbare Bühne erwarten.",
    notIdealWhen: "Öffentliche oder operative Bereiche des Vereins sind die Zielgruppe.",
    setupTip: "Zeige Premium-Sponsors in exklusiven Slots ohne Konkurrenz anderer Logos.",
    firstRecommendedAction: "Premium-Sponsor-Logos in hoher Auflösung hochladen und Rotationsfolge festlegen.",
    previewTokens: { bg: "#0c0c14", text: "#f0f0f5", accent: "#a78bfa" },
  },
  {
    key: "facility-operations",
    name: "Facility Operations",
    mode: "LIGHT",
    description: "Informationsdichtes Layout für Betriebsteams mit Platzbelegung, Helferplanung und Meldungen.",
    bestUseCase: "Facility manager screen, operations control room",
    recommendedScreens: ["pitch-allocation", "full-schedule", "roles-overview", "internal-announcements"],
    layoutRhythm: "date-time-header → pitch-grid → full-day-schedule → roles-strip → announcements",
    sponsorVisibilityLevel: "none",
    scheduleDensity: "full",
    alertAnnouncementSupport: true,
    bestUsedWhen: "Betriebsverantwortliche und Platzwarte brauchen Belegung, Helfer und Zeitplan auf einen Blick.",
    notIdealWhen: "Öffentliche Bereiche oder nicht-operative Mitarbeiter sind die Zielgruppe.",
    setupTip: "Verbinde Platzbelegungsplan und Helferrollen direkt damit der Board immer aktuell ist.",
    firstRecommendedAction: "Tagesansicht mit Platz-Belegungsplan und Hauptverantwortlichen einrichten.",
    previewTokens: { bg: "#f0fdf4", text: "#14532d", accent: "#22c55e" },
  },
];

export function getInfoboardPresetByKey(key: string): InfoboardPreset | undefined {
  return INFOBOARD_PRESETS.find((p) => p.key === key);
}

export const INFOBOARD_MODE_LABELS: Record<InfoboardMode, string> = {
  LIGHT: "Hell",
  DARK: "Dunkel",
  AUTO: "Automatisch",
};
