-- ---------------------------------------------------------------------------
-- STAGE Registration Seed Patch
--
-- Inserts 16 synthetic demo registrations for the FC Allschwil tenant
-- (tenantId = 'cmomwboak0000tsf3zzivrs46') into the STAGE database.
-- NOTE: The FC Allschwil tenant ID on STAGE is 'cmomwboak0000tsf3zzivrs46'.
-- The originally referenced ID 'cmomwboak0000tsf3zzivrs46' does not exist on STAGE.
--
-- All personal data is entirely synthetic — no real names, emails, or phone
-- numbers are used.  Matches the records defined in prisma/seed-demo.ts.
--
-- Safe to re-run: ON CONFLICT (id) DO NOTHING ensures idempotency.
-- ---------------------------------------------------------------------------

INSERT INTO "Registration" (
  "id",
  "tenantId",
  "type",
  "status",
  "firstName",
  "lastName",
  "email",
  "phone",
  "birthYear",
  "message",
  "payloadJson",
  "source",
  "submittedAt",
  "createdAt",
  "updatedAt"
) VALUES
  (
    'seed-demo-registration-001',
    'cmomwboak0000tsf3zzivrs46',
    'PROBETRAINING',
    'NEW',
    'Luca',
    'Muster',
    'kontakt.muster.001@example.com',
    '+41 79 000 00 01',
    2020,
    'Anmeldung gemeinsam mit Bruder.',
    '{"contactName":"M. Muster"}',
    'WEBSITE',
    NOW(),
    NOW(),
    NOW()
  ),
  (
    'seed-demo-registration-002',
    'cmomwboak0000tsf3zzivrs46',
    'PROBETRAINING',
    'NEW',
    'Noah',
    'Muster',
    'kontakt.muster.001@example.com',
    '+41 79 000 00 01',
    2019,
    'Anmeldung gemeinsam mit Bruder.',
    '{"contactName":"M. Muster"}',
    'WEBSITE',
    NOW(),
    NOW(),
    NOW()
  ),
  (
    'seed-demo-registration-003',
    'cmomwboak0000tsf3zzivrs46',
    'PROBETRAINING',
    'NEW',
    'Emma',
    'Beispiel',
    'kontakt.beispiel.003@example.com',
    '+41 79 000 00 03',
    2019,
    'Anfrage für Probetraining und Trainingszeiten.',
    '{"contactName":"O. Beispiel"}',
    'WEBSITE',
    NOW(),
    NOW(),
    NOW()
  ),
  (
    'seed-demo-registration-004',
    'cmomwboak0000tsf3zzivrs46',
    'PROBETRAINING',
    'NEW',
    'Jonas',
    'Demo',
    'kontakt.demo.004@example.com',
    '+41 76 000 00 04',
    2017,
    NULL,
    '{"contactName":"R. Demo"}',
    'WEBSITE',
    NOW(),
    NOW(),
    NOW()
  ),
  (
    'seed-demo-registration-005',
    'cmomwboak0000tsf3zzivrs46',
    'PROBETRAINING',
    'NEW',
    'Lars',
    'Testfall',
    'kontakt.testfall.005@example.com',
    '+41 79 000 00 05',
    2016,
    'Bereits auf der Warteliste.',
    '{"contactName":"R. Testfall"}',
    'WEBSITE',
    NOW(),
    NOW(),
    NOW()
  ),
  (
    'seed-demo-registration-006',
    'cmomwboak0000tsf3zzivrs46',
    'PROBETRAINING',
    'NEW',
    'Kiran',
    'Synthese',
    'kontakt.synthese.006@example.com',
    '+41 78 000 00 06',
    2016,
    NULL,
    '{"contactName":"T. Synthese"}',
    'WEBSITE',
    NOW(),
    NOW(),
    NOW()
  ),
  (
    'seed-demo-registration-007',
    'cmomwboak0000tsf3zzivrs46',
    'PROBETRAINING',
    'NEW',
    'Elisa',
    'Probe',
    'kontakt.probe.007@example.com',
    '+41 78 000 00 07',
    2016,
    NULL,
    '{"contactName":"A. Probe"}',
    'WEBSITE',
    NOW(),
    NOW(),
    NOW()
  ),
  (
    'seed-demo-registration-008',
    'cmomwboak0000tsf3zzivrs46',
    'PROBETRAINING',
    'NEW',
    'Sofia',
    'Fiktiv',
    'kontakt.fiktiv.008@example.com',
    '+41 78 000 00 08',
    2016,
    NULL,
    '{"contactName":"C. Fiktiv"}',
    'WEBSITE',
    NOW(),
    NOW(),
    NOW()
  ),
  (
    'seed-demo-registration-009',
    'cmomwboak0000tsf3zzivrs46',
    'PROBETRAINING',
    'NEW',
    'Noel',
    'Platzhalter',
    'kontakt.platzhalter.009@example.com',
    '+41 79 000 00 09',
    2020,
    NULL,
    '{"contactName":"R. Platzhalter"}',
    'WEBSITE',
    NOW(),
    NOW(),
    NOW()
  ),
  (
    'seed-demo-registration-010',
    'cmomwboak0000tsf3zzivrs46',
    'PROBETRAINING',
    'NEW',
    'Arsenio',
    'Dummydata',
    'kontakt.dummydata.010@example.com',
    '+41 76 000 00 10',
    2013,
    NULL,
    '{"contactName":"B. Dummydata"}',
    'WEBSITE',
    NOW(),
    NOW(),
    NOW()
  ),
  (
    'seed-demo-registration-011',
    'cmomwboak0000tsf3zzivrs46',
    'PROBETRAINING',
    'NEW',
    'Isaiah',
    'Testuser',
    'kontakt.testuser.011@example.com',
    '+41 76 000 00 11',
    2014,
    'Bruder spielt bereits im C1.',
    '{"contactName":"B. Testuser"}',
    'WEBSITE',
    NOW(),
    NOW(),
    NOW()
  ),
  (
    'seed-demo-registration-012',
    'cmomwboak0000tsf3zzivrs46',
    'PROBETRAINING',
    'NEW',
    'Leon',
    'Sampledata',
    'kontakt.sampledata.012@example.com',
    '+41 79 000 00 12',
    2013,
    'Aktuell D9 Promotion beim Demo FC.',
    '{"contactName":"N. Sampledata"}',
    'WEBSITE',
    NOW(),
    NOW(),
    NOW()
  ),
  (
    'seed-demo-registration-013',
    'cmomwboak0000tsf3zzivrs46',
    'PROBETRAINING',
    'NEW',
    'Marie',
    'Testdaten',
    'kontakt.testdaten.013@example.com',
    '+41 79 000 00 13',
    2011,
    NULL,
    '{"contactName":"A. Testdaten"}',
    'WEBSITE',
    NOW(),
    NOW(),
    NOW()
  ),
  (
    'seed-demo-registration-014',
    'cmomwboak0000tsf3zzivrs46',
    'PROBETRAINING',
    'NEW',
    'Ecrin',
    'Anfrage',
    'kontakt.anfrage.014@example.com',
    '+41 78 000 00 14',
    2013,
    'Interesse an einem Probetraining bei den D- oder C-Junioren.',
    NULL,
    'WEBSITE',
    NOW(),
    NOW(),
    NOW()
  ),
  (
    'seed-demo-registration-015',
    'cmomwboak0000tsf3zzivrs46',
    'SPIELERANMELDUNG',
    'NEW',
    'Tobias',
    'Spielertest',
    'kontakt.spielertest.015@example.com',
    '+41 77 000 00 15',
    2003,
    E'Demo FC U13-U14\nDemo FC U18\nDemo FC Aktive',
    NULL,
    'WEBSITE',
    NOW(),
    NOW(),
    NOW()
  ),
  (
    'seed-demo-registration-016',
    'cmomwboak0000tsf3zzivrs46',
    'SPIELERANMELDUNG',
    'NEW',
    'Claudio',
    'Demospieler',
    'kontakt.demospieler.016@example.com',
    '+41 78 000 00 16',
    1990,
    'Ehemaliger Leistungsfussballer mit Interesse an einem ambitionierten Team.',
    NULL,
    'WEBSITE',
    NOW(),
    NOW(),
    NOW()
  )
ON CONFLICT (id) DO NOTHING;
